In [7]:
!python -m pip install scikit-image;





   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 4.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.9 MB 2.8 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/12.9 MB 2.6 MB/s eta 0:00:05
   ------ --------------------------------- 2.1/12.9 MB 2.6 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.9 MB 2.5 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.9 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.9 MB 2.4 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.9 MB 2.4 MB/s eta 0:00:04
   -------------- ------------------------- 4.7/12.9 MB 2.4 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.9 MB 2.4 MB/s eta 0:00:04
   ----------------- ---------------------- 5.5/12.9 MB 2.4 MB/s eta 0:00:04
   ------------------ --------------------- 6.0/12.9 MB 2.4 MB/s eta 0:00:03
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
!python -m pip install numpy as np;


ERROR: Could not find a version that satisfies the requirement as (from versions: none)

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for as


In [ ]:

from skimage.feature import graycomatrix, graycoprops
import numpy as np
from PIL import Image

def calculate_glcm_contrast(image_path):
  """Calculates the contrast feature of the GLCM for a given image.

  Args:
    image_path: The path to the image file.

  Returns:
    The contrast value from the GLCM, or None if an error occurs.
  """
  try:
    # Open the image using Pillow library & Convert to grayscale
    img = Image.open(image_path).convert('L')

    # Convert the image to a NumPy array
    image_array = np.array(img)

    # Calculate the GLCM
    glcm = graycomatrix(image_array, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)


    contrast = graycoprops(glcm, 'contrast')[0, 0]

    return contrast

  except FileNotFoundError:
    print(f"Error: Image file not found at {image_path}")
    return None
  except Exception as e:
    print(f"An error occurred: {e}")
    return None


# Example Usage
image_path = 'https://i.ibb.co/G4dG8s3K/IMG-20250301-172740046-HDR.jpg'  # Replace with your image path
contrast_value = calculate_glcm_contrast(image_path)

if contrast_value is not None:
  print(f"GLCM Contrast: {contrast_value}")


Error: Image file not found at https://i.ibb.co/G4dG8s3K/IMG-20250301-172740046-HDR.jpg


In [ ]:
from skimage.feature import graycomatrix, graycoprops
import numpy as np
from PIL import Image
import requests
from io import BytesIO

def calculate_glcm_contrast(image_path):
    """Calculates the contrast feature of the GLCM for a given image (local path or URL)."""
    try:
        # Check if the path is a URL
        if image_path.startswith(('http://', 'https://')):
            # Download the image from the URL
            response = requests.get(image_path)
            response.raise_for_status()  # Raise error for bad status codes
            img = Image.open(BytesIO(response.content)).convert('L')  # Convert to grayscale
        else:
            # Open local image
            img = Image.open(image_path).convert('L')

        image_array = np.array(img)
        glcm = graycomatrix(image_array, distances=[1], angles=[0], levels=256, symmetric=True, normed=True)
        contrast = graycoprops(glcm, 'contrast')[0, 0]
        return contrast

    except Exception as e:
        print(f"Error: {e}")
        return None

# Example Usage
image_url = 'https://i.ibb.co/G4dG8s3K/IMG-20250301-172740046-HDR.jpg'  # Replace with a valid URL
contrast_value = calculate_glcm_contrast(image_url)

if contrast_value is not None:
    print(f"GLCM Contrast: {contrast_value}")


GLCM Contrast: 503.67975697281935


In [ ]:
# Example Usage
image_url = 'https://i.postimg.cc/dVn8QQVx/Whats-App-Image-2025-03-01-at-5-41-25-PM.jpg'  # Replace with a valid URL
contrast_value = calculate_glcm_contrast(image_url)

if contrast_value is not None:
    print(f"GLCM Contrast: {contrast_value}")

GLCM Contrast: 180.17513687150839


In [2]:
!python -m pip install numpy
import numpy as np

np.digitize([[2,3,4,6,7],[3,5,82,34,2]],np.linspace(2,82, 10 + 1))


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


array([[ 1,  1,  1,  1,  1],
       [ 1,  1, 11,  5,  1]], dtype=int64)

In [13]:
np.linspace(2,82,10+1) #Checking whether linspace is the same as function I wrote

array([ 2., 10., 18., 26., 34., 42., 50., 58., 66., 74., 82.])

In [6]:
!python -m pip install opencv-python


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import cv2
import numpy as np
def fast_glcm(img, vmin=0, vmax=255, nbit=8, kernel_size=5):
    mi, ma = vmin, vmax
    ks = kernel_size
    h,w = img.shape

    # digitize
    bins = np.linspace(mi, ma+1, nbit+1)
    gl1 = np.digitize(img, bins) - 1
    print(f"{gl1} After digitize #1")
    gl2 = np.append(gl1[:,1:], gl1[:,-1:], axis=1)

    print(f"{gl2} After digitize #2")
    # make glcm
    glcm = np.zeros((nbit, nbit, h, w), dtype=np.uint8)
    for i in range(nbit):
        for j in range(nbit):
            mask = ((gl1==i) & (gl2==j))
            glcm[i,j, mask] = 1

    kernel = np.ones((ks, ks), dtype=np.uint8)
    for i in range(nbit):
        for j in range(nbit):
            glcm[i,j] = cv2.filter2D(glcm[i,j], -1, kernel)

    glcm = glcm.astype(np.float32)
    return glcm

fast_glcm(np.array([[2,3,4,6,7],[3,5,82,34,2]]), vmin=2, vmax=83, nbit=11, kernel_size=5)

[[ 0  0  0  0  0]
 [ 0  0 10  4  0]] After digitize #1
[[ 0  0  0  0  0]
 [ 0 10  4  0  0]] After digitize #2


array([[[[17., 17., 19., 17., 17.],
         [13., 13., 16., 13., 13.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        ...,

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 4.,  4.,  2.,  2.,  0.],
         [ 6.,  6.,  3.,  3.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        ...,

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

      

In [15]:
np.linspace(2,56,4)


array([ 2., 20., 38., 56.])

In [4]:
np.linspace(2,34,10)

array([ 2.        ,  5.55555556,  9.11111111, 12.66666667, 16.22222222,
       19.77777778, 23.33333333, 26.88888889, 30.44444444, 34.        ])

In [5]:
np.digitize([[1,3,4,6,7],[3,5,24,34,2]],np.linspace(2,34, 10))



array([[ 0,  1,  1,  2,  2],
       [ 1,  1,  7, 10,  1]], dtype=int64)